// Pokémon Name Mappings & Ignore Configuration
// This file helps manage discrepancies between different naming conventions
// for Pokémon forms across different data sources

module.exports = {
  IgnoreIfNonCanonicalMega: [
    "luxray-mega",
    "torterra-mega",
    "empoleon-mega-o",
    "empoleon-mega-d",
    "infernape-mega",
    "butterfree-mega",
    "machamp-mega",
    "kingler-mega",
    "lapras-mega",
    "snorlax-mega",
    "garbodor-mega",
    "orbeetle-mega",
    "drednaw-mega",
    "coalossal-mega",
    "flapple-mega",
    "appletun-mega",
    "sandaconda-mega",
    "toxtricity-mega",
    "centiskorch-mega",
    "grimmsnarl-mega",
    "copperajah-mega",
    "slaking-mega",
    "roserade-mega",
    "dusknoir-mega",
  ],
  IgnoreIfNonCanonicalPrimal: ["dialga-primal", "palkia-primal"],
  IgnoreIfTotemForm: [
    "raticate-alola-totem",
    "marowak-alola-totem",
    "mimikyu-busted-totem",
  ],
  IgnoreIfSpecialEntry: ["egg"],

  IgnoreIfTera: [
    "ogerpon-teal-tera",
    "ogerpon-wellspring-tera",
    "ogerpon-hearthflame-tera",
    "ogerpon-cornerstone-tera",
  ],

  MapToBaseForm: {
    "gimmighoul-chest": "gimmighoul",
    "zacian-hero": "zacian",
    "zamazenta-hero": "zamazenta",
    "hoopa-confined": "hoopa",
    "terapagos-normal": "terapagos",
    "xerneas-neutral": "xerneas",
    "xerneas-active": "xerneas",
    "castform-normal": "castform",
    "sinistea-phony": "sinistea",
    "sinistea-antique": "sinistea",
    "polteageist-phony": "polteageist",
    "polteageist-antique": "polteageist",
    "pichu-spiky-eared": "pichu",
    "burmy-plant": "burmy",
    "burmy-sandy": "burmy",
    "burmy-trash": "burmy",
    "mothim-plant": "mothim",
    "mothim-sandy": "mothim",
    "mothim-trash": "mothim",
    "cherrim-overcast": "cherrim",
    "cherrim-sunshine": "cherrim",
    "shellos-west": "shellos",
    "shellos-east": "shellos",
    "gastrodon-west": "gastrodon",
    "gastrodon-east": "gastrodon",
    "deerling-spring": "deerling",
    "deerling-summer": "deerling",
    "deerling-autumn": "deerling",
    "deerling-winter": "deerling",
    "sawsbuck-spring": "sawsbuck",
    "sawsbuck-summer": "sawsbuck",
    "sawsbuck-autumn": "sawsbuck",
    "sawsbuck-winter": "sawsbuck",
    "scatterbug-icy-snow": "scatterbug",
    "scatterbug-polar": "scatterbug",
    "scatterbug-tundra": "scatterbug",
    "scatterbug-continental": "scatterbug",
    "scatterbug-garden": "scatterbug",
    "scatterbug-elegant": "scatterbug",
    "scatterbug-meadow": "scatterbug",
    "scatterbug-modern": "scatterbug",
    "scatterbug-marine": "scatterbug",
    "scatterbug-archipelago": "scatterbug",
    "scatterbug-high-plains": "scatterbug",
    "scatterbug-sandstorm": "scatterbug",
    "scatterbug-river": "scatterbug",
    "scatterbug-monsoon": "scatterbug",
    "scatterbug-savanna": "scatterbug",
    "scatterbug-sun": "scatterbug",
    "scatterbug-ocean": "scatterbug",
    "scatterbug-jungle": "scatterbug",
    "scatterbug-fancy": "scatterbug",
    "scatterbug-pokeball": "scatterbug",
    "spewpa-icy-snow": "spewpa",
    "spewpa-polar": "spewpa",
    "spewpa-tundra": "spewpa",
    "spewpa-continental": "spewpa",
    "spewpa-garden": "spewpa",
    "spewpa-elegant": "spewpa",
    "spewpa-meadow": "spewpa",
    "spewpa-modern": "spewpa",
    "spewpa-marine": "spewpa",
    "spewpa-archipelago": "spewpa",
    "spewpa-high-plains": "spewpa",
    "spewpa-sandstorm": "spewpa",
    "spewpa-river": "spewpa",
    "spewpa-monsoon": "spewpa",
    "spewpa-savanna": "spewpa",
    "spewpa-sun": "spewpa",
    "spewpa-ocean": "spewpa",
    "spewpa-jungle": "spewpa",
    "spewpa-fancy": "spewpa",
    "spewpa-pokeball": "spewpa",
    "flabebe-red": "flabebe",
    "flabebe-yellow": "flabebe",
    "flabebe-orange": "flabebe",
    "flabebe-blue": "flabebe",
    "flabebe-white": "flabebe",
    "floette-red": "floette",
    "floette-yellow": "floette",
    "floette-orange": "floette",
    "floette-blue": "floette",
    "floette-white": "floette",
    "florges-red": "florges",
    "florges-yellow": "florges",
    "florges-orange": "florges",
    "florges-blue": "florges",
    "florges-white": "florges",
    "furfrou-natural": "furfrou",
    "furfrou-heart-trim": "furfrou",
    "furfrou-star-trim": "furfrou",
    "furfrou-diamond-trim": "furfrou",
    "furfrou-debutante-trim": "furfrou",
    "furfrou-matron-trim": "furfrou",
    "furfrou-dandy-trim": "furfrou",
    "furfrou-la-reine-trim": "furfrou",
    "furfrou-kabuki-trim": "furfrou",
    "furfrou-pharaoh-trim": "furfrou",
    "unown-b": "unown",
    "unown-c": "unown",
    "unown-d": "unown",
    "unown-e": "unown",
    "unown-f": "unown",
    "unown-g": "unown",
    "unown-h": "unown",
    "unown-i": "unown",
    "unown-j": "unown",
    "unown-k": "unown",
    "unown-l": "unown",
    "unown-m": "unown",
    "unown-n": "unown",
    "unown-o": "unown",
    "unown-p": "unown",
    "unown-q": "unown",
    "unown-r": "unown",
    "unown-s": "unown",
    "unown-t": "unown",
    "unown-u": "unown",
    "unown-v": "unown",
    "unown-w": "unown",
    "unown-x": "unown",
    "unown-y": "unown",
    "unown-z": "unown",
    "unown-exclamation": "unown",
    "unown-question": "unown",
    "arceus-normal": "arceus",
    "arceus-fighting": "arceus",
    "arceus-flying": "arceus",
    "arceus-poison": "arceus",
    "arceus-ground": "arceus",
    "arceus-rock": "arceus",
    "arceus-bug": "arceus",
    "arceus-ghost": "arceus",
    "arceus-steel": "arceus",
    "arceus-fire": "arceus",
    "arceus-water": "arceus",
    "arceus-grass": "arceus",
    "arceus-electric": "arceus",
    "arceus-psychic": "arceus",
    "arceus-ice": "arceus",
    "arceus-dragon": "arceus",
    "arceus-dark": "arceus",
    "arceus-fairy": "arceus",
    "silvally-normal": "silvally",
    "silvally-fighting": "silvally",
    "silvally-flying": "silvally",
    "silvally-poison": "silvally",
    "silvally-ground": "silvally",
    "silvally-rock": "silvally",
    "silvally-bug": "silvally",
    "silvally-ghost": "silvally",
    "silvally-steel": "silvally",
    "silvally-fire": "silvally",
    "silvally-water": "silvally",
    "silvally-grass": "silvally",
    "silvally-electric": "silvally",
    "silvally-psychic": "silvally",
    "silvally-ice": "silvally",
    "silvally-dragon": "silvally",
    "silvally-dark": "silvally",
    "silvally-fairy": "silvally",
    "genesect-douse": "genesect",
    "genesect-shock": "genesect",
    "genesect-burn": "genesect",
    "genesect-chill": "genesect",
    "maushold-three": "maushold-family-of-three",
    "maushold-four": "maushold-family-of-four",
  },
  GenderFormMapping: {
    "meowstic-m": "meowstic-male",
    "meowstic-f": "meowstic-female",
    "indeedee-m": "indeedee-male",
    "indeedee-f": "indeedee-female",
    "oinkologne-m": "oinkologne-male",
    "oinkologne-f": "oinkologne-female",
    "basculegion-m": "basculegion-male",
    "basculegion-f": "basculegion-female",
  },
  RegionalFormMapping: {
    "tauros-paldea-combat": "tauros-paldea-combat-breed",
    "tauros-paldea-blaze": "tauros-paldea-blaze-breed",
    "tauros-paldea-aqua": "tauros-paldea-aqua-breed",
  },
  MaskFormMapping: {
    "ogerpon-wellspring": "ogerpon-wellspring-mask",
    "ogerpon-hearthflame": "ogerpon-hearthflame-mask",
    "ogerpon-cornerstone": "ogerpon-cornerstone-mask",
  },
  PikachuCapMapping: {
    "pikachu-original": "pikachu-original-cap",
    "pikachu-hoenn": "pikachu-hoenn-cap",
    "pikachu-sinnoh": "pikachu-sinnoh-cap",
    "pikachu-unova": "pikachu-unova-cap",
    "pikachu-kalos": "pikachu-kalos-cap",
    "pikachu-alola": "pikachu-alola-cap",
    "pikachu-partner": "pikachu-partner-cap",
    "pikachu-world": "pikachu-world-cap",
  },
  PlumageFormMapping: {
    "squawkabilly-green": "squawkabilly-green-plumage",
    "squawkabilly-blue": "squawkabilly-blue-plumage",
    "squawkabilly-yellow": "squawkabilly-yellow-plumage",
    "squawkabilly-white": "squawkabilly-white-plumage",
  },
  NecrozmaFormMapping: {
    "necrozma-dusk-mane": "necrozma-dusk",
    "necrozma-dawn-wings": "necrozma-dawn",
  },
  VivillonFormMapping: {
    "vivillon-icy-snow": "vivillon",
    "vivillon-polar": "vivillon",
    "vivillon-tundra": "vivillon",
    "vivillon-continental": "vivillon",
    "vivillon-garden": "vivillon",
    "vivillon-elegant": "vivillon",
    "vivillon-meadow": "vivillon",
    "vivillon-modern": "vivillon",
    "vivillon-marine": "vivillon",
    "vivillon-archipelago": "vivillon",
    "vivillon-high-plains": "vivillon",
    "vivillon-sandstorm": "vivillon",
    "vivillon-river": "vivillon",
    "vivillon-monsoon": "vivillon",
    "vivillon-savanna": "vivillon",
    "vivillon-sun": "vivillon",
    "vivillon-ocean": "vivillon",
    "vivillon-jungle": "vivillon",
    "vivillon-fancy": "vivillon",
    "vivillon-pokeball": "vivillon",
  },
  MiniorMapping: {
    "minior-meteor-red": "minior-red-meteor",
    "minior-meteor-orange": "minior-orange-meteor",
    "minior-meteor-yellow": "minior-yellow-meteor",
    "minior-meteor-green": "minior-green-meteor",
    "minior-meteor-blue": "minior-blue-meteor",
    "minior-meteor-indigo": "minior-indigo-meteor",
    "minior-meteor-violet": "minior-violet-meteor",
    "minior-core-red": "minior-red",
    "minior-core-orange": "minior-orange",
    "minior-core-yellow": "minior-yellow",
    "minior-core-green": "minior-green",
    "minior-core-blue": "minior-blue",
    "minior-core-indigo": "minior-indigo",
    "minior-core-violet": "minior-violet",
  },
  AlcremieMapping: {
    "alcremie-strawberry-vanilla-cream": "alcremie",
    "alcremie-strawberry-ruby-cream": "alcremie",
    "alcremie-strawberry-matcha-cream": "alcremie",
    "alcremie-strawberry-mint-cream": "alcremie",
    "alcremie-strawberry-lemon-cream": "alcremie",
    "alcremie-strawberry-salted-cream": "alcremie",
    "alcremie-strawberry-ruby-swirl": "alcremie",
    "alcremie-strawberry-caramel-swirl": "alcremie",
    "alcremie-strawberry-rainbow-swirl": "alcremie",
    "alcremie-berry-vanilla-cream": "alcremie",
    "alcremie-berry-ruby-cream": "alcremie",
    "alcremie-berry-matcha-cream": "alcremie",
    "alcremie-berry-mint-cream": "alcremie",
    "alcremie-berry-lemon-cream": "alcremie",
    "alcremie-berry-salted-cream": "alcremie",
    "alcremie-berry-ruby-swirl": "alcremie",
    "alcremie-berry-caramel-swirl": "alcremie",
    "alcremie-berry-rainbow-swirl": "alcremie",
    "alcremie-love-vanilla-cream": "alcremie",
    "alcremie-love-ruby-cream": "alcremie",
    "alcremie-love-matcha-cream": "alcremie",
    "alcremie-love-mint-cream": "alcremie",
    "alcremie-love-lemon-cream": "alcremie",
    "alcremie-love-salted-cream": "alcremie",
    "alcremie-love-ruby-swirl": "alcremie",
    "alcremie-love-caramel-swirl": "alcremie",
    "alcremie-love-rainbow-swirl": "alcremie",
    "alcremie-star-vanilla-cream": "alcremie",
    "alcremie-star-ruby-cream": "alcremie",
    "alcremie-star-matcha-cream": "alcremie",
    "alcremie-star-mint-cream": "alcremie",
    "alcremie-star-lemon-cream": "alcremie",
    "alcremie-star-salted-cream": "alcremie",
    "alcremie-star-ruby-swirl": "alcremie",
    "alcremie-star-caramel-swirl": "alcremie",
    "alcremie-star-rainbow-swirl": "alcremie",
    "alcremie-clover-vanilla-cream": "alcremie",
    "alcremie-clover-ruby-cream": "alcremie",
    "alcremie-clover-matcha-cream": "alcremie",
    "alcremie-clover-mint-cream": "alcremie",
    "alcremie-clover-lemon-cream": "alcremie",
    "alcremie-clover-salted-cream": "alcremie",
    "alcremie-clover-ruby-swirl": "alcremie",
    "alcremie-clover-caramel-swirl": "alcremie",
    "alcremie-clover-rainbow-swirl": "alcremie",
    "alcremie-flower-vanilla-cream": "alcremie",
    "alcremie-flower-ruby-cream": "alcremie",
    "alcremie-flower-matcha-cream": "alcremie",
    "alcremie-flower-mint-cream": "alcremie",
    "alcremie-flower-lemon-cream": "alcremie",
    "alcremie-flower-salted-cream": "alcremie",
    "alcremie-flower-ruby-swirl": "alcremie",
    "alcremie-flower-caramel-swirl": "alcremie",
    "alcremie-flower-rainbow-swirl": "alcremie",
    "alcremie-ribbon-vanilla-cream": "alcremie",
    "alcremie-ribbon-ruby-cream": "alcremie",
    "alcremie-ribbon-matcha-cream": "alcremie",
    "alcremie-ribbon-mint-cream": "alcremie",
    "alcremie-ribbon-lemon-cream": "alcremie",
    "alcremie-ribbon-salted-cream": "alcremie",
    "alcremie-ribbon-ruby-swirl": "alcremie",
    "alcremie-ribbon-caramel-swirl": "alcremie",
    "alcremie-ribbon-rainbow-swirl": "alcremie",
  },
  OgerponTeraMapping: {
    "ogerpon-teal": "ogerpon",
  },
  ZygardeFormMapping: {
    "zygarde-10-aura-break": "zygarde-10",
  },
};

// Usage instructions:
// - IgnoreIfNonCanonicalMega: Mega evolutions that don't exist in official games
// - IgnoreIfNonCanonicalPrimal: Primal forms that don't exist in official games
// - IgnoreIfTotemForm: Totem Pokémon from Sun/Moon that need special handling
// - IgnoreIfSpecialEntry: Special entries that aren't actual Pokémon
// - MapToBaseForm: Forms that should be treated as their base form
// - GenderFormMapping: Maps abbreviated gender forms to full name versions
// - RegionalFormMapping: Regional form naming differences
// - MaskFormMapping: For Pokémon with mask/appearance forms
// - PikachuCapMapping: For Pikachu's different cap forms
// - PlumageFormMapping: For Squawkabilly's plumage forms
// - NecrozmaFormMapping: For Necrozma's fusion forms
// - VivillonFormMapping: Maps Vivillon pattern forms
// - MiniorMapping: Maps Minior color and state forms
// - AlcremieMapping: Maps Alcremie's many decoration variations
// - OgerponTeraMapping: Maps Ogerpon tera forms
// - ZygardeFormMapping: Maps Zygarde form variants
// - CompletelyIgnore: Entries to completely ignore in processing

// Note: This configuration can be expanded as needed for new forms or special cases
