import { getItemName } from "./itemData";
import { getTypeName } from "./typeInfo";
import { getMoveName } from "./moveData";
import { getNameKey } from "./pokemonData";

export const parseEvolutions: Record<number, (evo: number[]) => string> = {
  0: () => `None`,
  1: () => `Level up with friendship ≥ 220`,
  2: () => `Level up during the day with friendship ≥ 220`,
  3: () => `Level up at night with friendship ≥ 220`,
  4: (evo) => `Lvl ${evo[2]}`,
  5: () => `Pokémon is traded`,
  6: () => `Pokémon is traded while it's holding the specified item`,
  7: (evo) => `${getItemName(evo[2])}`,
  8: (evo) => `Lvl ${evo[2]} + Atk>Def`,
  9: (evo) => `Lvl ${evo[2]} with Atk=Def`,
  10: (evo) => `Lvl ${evo[2]} with Atk<Def`,
  11: (evo) => `Lvl ${evo[2]} with a  pid`,
  12: (evo) => `Lvl ${evo[2]} with a Cascoon pid`,
  13: (evo) => `Lvl ${evo[2]}`,
  14: (evo) => `Lvl ${evo[2]}`,
  15: (evo) => `Level up with beauty ≥ ${evo[2]}`,
  16: (evo) => `Lvl ${evo[2]}, is female`,
  17: (evo) => `Lvl ${evo[2]}, is male`,
  18: (evo) => `Lvl ${evo[2]}, is night`,
  19: (evo) => `Lvl ${evo[2]}, is day`,
  20: (evo) => `Lvl ${evo[2]}, is dusk`,
  21: (evo) => `Level up, with ${getItemName(evo[2])} at day`,
  22: (evo) => `Level up, with ${getItemName(evo[2])} at night`,
  23: (evo) => `Level up, knowing ${getMoveName(evo[2])}`,
  24: (evo) =>
    `Level up with friendship ≥ 220, knows ${getTypeName(evo[2])} move`,
  25: (evo) => `Level up in ${evo[2]}`,
  26: (evo) => `${evo[2]} on male`,
  27: (evo) => `${evo[2]} on female`,
  28: (evo) => `Lvl ${evo[2]} with overworld rain`,
  29: (evo) => `Level up with ${getNameKey(evo[2])} in party`,
  30: (evo) => `Lvl ${evo[2]} with a Dark Type in party`,
  31: (evo) => `Traded for ${evo[2]}`,
  32: () => `Level up at specific place`,
  33: (evo) => `Lvl ${evo[2]}, with Amped nature`,
  34: (evo) => `Lvl ${evo[2]}, with Low Key nature`,
  35: (evo) => `${evo[2]} crits in battle`,
  36: () => `Pokémon has specified HP below max, then player interacts trigger`,
  37: () => `Scroll of Darkness`,
  38: () => `Scroll of Waters`,
  39: (evo) => `use ${evo[2]}, at nightime`,
  40: (evo) => `use ${evo[2]}, in daytime`,
  41: (evo) => `Level up, with ${evo[2]}`,
  42: (evo) => `Lvl ${evo[2]} during fog in the overworld`,
  43: () =>
    `Level up, knows specified move, has a personality value with a modulus of 0`,
  44: () =>
    `Level up, knows specified move, has a personality value with a modulus of 1-99`,
  45: (evo) =>
    `Lvl ${evo[2]} in battle with a personality value with a modulus of 0`,
  46: (evo) =>
    `Lvl ${evo[2]} in battle with a personality value with a modulus of 1-99`,
  47: (evo) => `Level up after using ${evo[2]} 20 times`,
  48: (evo) => `Level up after ${evo[2]}% recoil if male`,
  49: (evo) => `Level up after ${evo[2]}% recoil if female`,
  50: (evo) => `Level up after getting ${evo[2]} x999`,
  51: (evo) => `Level up after KOing 3 of same species, holding ${evo[2]}`,
  52: (evo) => `Level up after ${evo[2]} steps`,
};

export const parseShortEvolutions: Record<number, (evo: number[]) => string> = {
  0: () => `None`,
  1: () => `Level up with friendship ≥ 220`,
  2: () => `Level up during the day with friendship ≥ 220`,
  3: () => `Level up at night with friendship ≥ 220`,
  4: (evo) => `Lvl ${evo[2]}`,
  5: () => `Pokémon is traded`,
  6: () => `Pokémon is traded while it's holding the specified item`,
  7: (evo) => `${getItemName(evo[2])}`,
  8: (evo) => `Lvl ${evo[2]} with Atk>Def`,
  9: (evo) => `Lvl ${evo[2]} with Atk=Def`,
  10: (evo) => `Lvl ${evo[2]} with Atk<Def`,
  11: (evo) => `Lvl ${evo[2]}`,
  12: (evo) => `Lvl ${evo[2]}`,
  13: (evo) => `Lvl ${evo[2]}`,
  14: (evo) => `Lvl ${evo[2]}`,
  15: () => `Lvl + Beaut`,
  16: (evo) => `Lvl ${evo[2]} (F)`,
  17: (evo) => `Lvl ${evo[2]}, (M)`,
  18: (evo) => `Lvl ${evo[2]} (Night)`,
  19: (evo) => `Lvl ${evo[2]} (Day)`,
  20: (evo) => `Lvl ${evo[2]} (Dusk)`,
  21: (evo) => `Level up, with ${getItemName(evo[2])} (Day)`,
  22: (evo) => `Level up, with ${getItemName(evo[2])} (Night)`,
  23: (evo) => `Level up, knowing ${getMoveName(evo[2])}`,
  24: (evo) =>
    `Lvl + ♥ + ${getTypeName(evo[2])} move`,
  25: (evo) => `Lvl + ${evo[2]}`,
  26: (evo) => `${evo[2]} (Male)`,
  27: (evo) => `${evo[2]} (Female)`,
  28: (evo) => `Lvl ${evo[2]} with overworld rain`,
  29: (evo) => `Level up with ${getNameKey(evo[2])} in party`,
  30: (evo) => `Lvl ${evo[2]} with a Dark Type in party`,
  31: (evo) => `Traded for ${evo[2]}`,
  32: () => `Level up at specific place`,
  33: (evo) => `Lvl ${evo[2]}, with Amped nature`,
  34: (evo) => `Lvl ${evo[2]}, with Low Key nature`,
  35: (evo) => `${evo[2]} crits in battle`,
  36: () => `Pokémon has specified HP below max, then player interacts trigger`,
  37: () => `Scroll of Darkness`,
  38: () => `Scroll of Waters`,
  39: (evo) => `use ${evo[2]}, at nightime`,
  40: (evo) => `use ${evo[2]}, in daytime`,
  41: (evo) => `Level up, with ${evo[2]}`,
  42: (evo) => `Lvl ${evo[2]} during fog in the overworld`,
  43: () =>
    `Level up, knows specified move, has a personality value with a modulus of 0`,
  44: () =>
    `Level up, knows specified move, has a personality value with a modulus of 1-99`,
  45: (evo) =>
    `Lvl ${evo[2]} in battle with a personality value with a modulus of 0`,
  46: (evo) =>
    `Lvl ${evo[2]} in battle with a personality value with a modulus of 1-99`,
  47: (evo) => `Level up after using ${evo[2]} 20 times`,
  48: (evo) => `Level up after ${evo[2]}% recoil if male`,
  49: (evo) => `Level up after ${evo[2]}% recoil if female`,
  50: (evo) => `Level up after getting ${evo[2]} x999`,
  51: (evo) => `Level up after KOing 3 of same species, holding ${evo[2]}`,
  52: (evo) => `Level up after ${evo[2]} steps`,
};
