name: Preview Deploy

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: BASE_PATH='/' npm run build

      - name: Set CNAME for Preview
        run : echo 'dex.emeraldimperium.net' > ./dist/CNAME

      - name: Deploy to Preview Repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          # yamllint disable-line rule:truthy
          deploy_key: ${{ secrets.PREVIEW_DEPLOY_KEY }}
          external_repository: izrofid/eidex-preview
          publish_dir: ./dist
          publish_branch: gh-pages
